
[env]
TERM = "xterm-256color"

[font]
size = 19.5

[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[window]
option_as_alt = "Both"
decorations = "buttonless"
opacity = 0.95

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 10
y = 10

[cursor]
style = "Block"
unfocused_hollow = true

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]
