customCommands:
  - key: <c-a>
    description: Pick AI commit (copy)
    command: cat ~/.claude/commands/gen-commit-msg.md | claude --allowedTools 'Bash(git commit -m:*)' -p
    context: files
    output: terminal