customCommands:
  - key: '<c-a>'
    description: 'Pick AI commit'
    command: 'aicommit2'
    context: 'files'
    subprocess: true
    showOutput: true
  - key: '<c-n>'
    description: 'Pick AI commit (no verify)'
    command: 'aicommit2 --no-verify'
    context: 'files'
    subprocess: true