#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####

sketchybar --bar position=top height=25 blur_radius=30 color=$BAR_COLOR

##### Changing Defaults #####

default=(
    padding_left=0
    padding_right=0
    background.color="$ITEM_BG_COLOR"
    background.corner_radius=6
    background.height=25
    icon.font="BerkeleyMono Nerd Font Mono:Bold:15.0"
    label.font="BerkeleyMono Nerd Font Mono:Bold:14.0"
    icon.color=$WHITE
    icon.y_offset=1
    label.color=$WHITE
    label.y_offset=1
    icon.padding_left=5
    icon.padding_right=5
    label.padding_left=5
    label.padding_right=5
)
sketchybar --default "${default[@]}"

##### Left side items #####

source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

##### Right side items #####

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"

##### Force all scripts to run the first time (never do this in a script) #####

sketchybar --update
